"""
compliance.py

Produce a framework-mapped compliance document from findings produced by the
audit engine. Minimal, test-friendly implementation: accepts a list of findings
(each finding is a dict with keys: id, title, category, severity, description,
remediation, frameworks (list of {framework,control} mappings), evidence).

Provides:
- generate_compliance_report(findings, profile_name=None) -> str (markdown)
- write_compliance_report(path, findings, profile_name=None)

This module is intentionally lightweight and deterministic so it can be used in
unit tests and in pilot handoffs without external dependencies.
"""
from datetime import datetime
from typing import List, Dict, Optional


def _severity_emoji(sev: str) -> str:
    sev = (sev or "").lower()
    if sev in ("critical", "high"):
        return "🔴"
    if sev in ("medium", "moderate"):
        return "🟡"
    if sev in ("low", "info", "informational"):
        return "✅"
    return "⚪"


def generate_compliance_report(findings: List[Dict], profile_name: Optional[str] = None) -> str:
    """Return a markdown compliance report summarizing findings and mapping to frameworks."""
    now = datetime.utcnow().replace(microsecond=0).isoformat() + "Z"
    total = len(findings or [])
    passes = sum(1 for f in findings if f.get("result") == "PASS")
    fails = sum(1 for f in findings if f.get("result") == "FAIL")

    header = [
        f"# M.A.R.K. Sentinel — Compliance Report",
        f"Generated: {now}",
    ]
    if profile_name:
        header.append(f"Profile: {profile_name}")
    header.append("")

    summary = [
        "## Summary",
        f"Total checks: {total}",
        f"Passes: {passes}",
        f"Failures: {fails}",
        "",
    ]

    sections = ["## Findings", ""]
    if not findings:
        sections += ["No findings were provided.", ""]
    else:
        # Group by category for readability
        by_cat = {}
        for f in findings:
            cat = f.get("category", "UNCATEGORIZED")
            by_cat.setdefault(cat, []).append(f)

        for cat, items in sorted(by_cat.items()):
            sections.append(f"### {cat} ({len(items)})")
            sections.append("")
            for f in items:
                eid = f.get("id", "UNKNOWN")
                title = f.get("title", "Untitled check")
                sev = f.get("severity", "info")
                res = f.get("result", "UNKNOWN")
                emoji = _severity_emoji(sev) if res != "PASS" else "✅"
                sections.append(f"- **{eid} — {title}** — {emoji}  ")
                if f.get("description"):
                    sections.append(f"  - Description: {f['description']}")
                if f.get("remediation"):
                    sections.append(f"  - Remediation: {f['remediation']}")
                if f.get("frameworks"):
                    mappings = ", ".join([f"{m.get('framework')}/{m.get('control')}" for m in f.get("frameworks")])
                    sections.append(f"  - Framework mappings: {mappings}")
                if f.get("evidence"):
                    sections.append(f"  - Evidence: {f['evidence']}")
                sections.append("")

    footer = ["----", "Generated by M.A.R.K. Sentinel — https://example.com/mark", ""]

    report = "\n".join(header + summary + sections + footer)
    return report


def write_compliance_report(path: str, findings: List[Dict], profile_name: Optional[str] = None) -> None:
    content = generate_compliance_report(findings, profile_name=profile_name)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


# Minimal CLI for manual invocation during handoffs (keeps dependencies low)
if __name__ == "__main__":
    import json, sys
    if len(sys.argv) < 3:
        print("Usage: compliance.py <findings.json> <out.md> [profile]")
        sys.exit(2)
    findings_path = sys.argv[1]
    out_path = sys.argv[2]
    profile = sys.argv[3] if len(sys.argv) > 3 else None
    with open(findings_path, "r", encoding="utf-8") as fh:
        findings = json.load(fh)
    write_compliance_report(out_path, findings, profile)
    print(f"Wrote {out_path}")
