"""
M.A.R.K. Sentinel — Kyverno ClusterPolicy generator
Produces Kyverno admission control policies that enforce M.A.R.K. controls
on Kubernetes AI workloads.

Apply: kubectl apply -f mark_sentinel_kyverno.yaml
Target: Deployments/Pods/StatefulSets with label mark-sentinel.io/ai-workload: "true"

Policy index:
  mark-sentinel-ai-deploy-001  No plaintext credentials in env vars  (AI-DEPLOY-001)
  mark-sentinel-ai-deploy-005  Require TLS on AI Ingress resources   (AI-DEPLOY-005)
  mark-sentinel-ai-deploy-006  Require CPU/memory resource limits    (AI-DEPLOY-006)
  mark-sentinel-ai-agent-001   Require non-root securityContext      (AI-AGENT-001)
  mark-sentinel-ai-deploy-004  Disallow hostNetwork on AI workloads  (AI-DEPLOY-004)
  mark-sentinel-ai-supply-005  Require pinned image tag              (AI-SUPPLY-005)
"""
from datetime import date


_AI_LABEL = 'mark-sentinel.io/ai-workload: "true"'

_WORKLOAD_KINDS = ["Deployment", "StatefulSet", "Pod"]


def _meta(name: str, check_id: str, title: str, action: str, today: str) -> str:
    return f"""\
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {name}
  annotations:
    mark-sentinel.io/check-id: "{check_id}"
    mark-sentinel.io/title: "{title}"
    mark-sentinel.io/generated: "{today}"
    policies.kyverno.io/title: "M.A.R.K. Sentinel — {check_id}"
    policies.kyverno.io/description: >-
      Enforces M.A.R.K. Sentinel control {check_id}: {title}.
      Generated by M.A.R.K. Sentinel AI Security Audit Tool.
spec:
  validationFailureAction: {action}
  background: true"""


def _policy_no_plaintext_creds(today: str, action: str) -> str:
    header = _meta(
        "mark-sentinel-ai-deploy-001",
        "AI-DEPLOY-001",
        "API Keys Not Exposed in Env Vars",
        action,
        today,
    )
    return header + """
  rules:
    - name: disallow-plaintext-ai-credentials
      match:
        any:
        - resources:
            kinds:
            - Deployment
            - StatefulSet
            - Pod
            selector:
              matchLabels:
                mark-sentinel.io/ai-workload: "true"
      validate:
        message: >-
          [AI-DEPLOY-001] AI workload containers must not set API keys, tokens, or
          passwords as plaintext env var values. Use secretKeyRef instead.
        foreach:
          - list: >-
              request.object.spec.template.spec.containers[] |
              map(&env[] || `[]`, @) | [] | []
            deny:
              conditions:
                all:
                - key: "{{ element.value || '' }}"
                  operator: NotEquals
                  value: ""
                - key: "{{ element.name }}"
                  operator: Match
                  value: "(?i).*(API_KEY|SECRET|TOKEN|PASSWORD|OPENAI|ANTHROPIC|GEMINI|GROQ).*"
"""


def _policy_require_resource_limits(today: str, action: str) -> str:
    header = _meta(
        "mark-sentinel-ai-deploy-006",
        "AI-DEPLOY-006",
        "Resource Limits Configured on AI Containers",
        action,
        today,
    )
    return header + """
  rules:
    - name: require-cpu-memory-limits
      match:
        any:
        - resources:
            kinds:
            - Deployment
            - StatefulSet
            - Pod
            selector:
              matchLabels:
                mark-sentinel.io/ai-workload: "true"
      validate:
        message: >-
          [AI-DEPLOY-006] AI workload containers must specify CPU and memory limits
          to prevent resource exhaustion and enable rate-limit enforcement.
        pattern:
          spec:
            =(template):
              spec:
                containers:
                - resources:
                    limits:
                      cpu: "?*"
                      memory: "?*"
"""


def _policy_require_non_root(today: str, action: str) -> str:
    header = _meta(
        "mark-sentinel-ai-agent-001",
        "AI-AGENT-001",
        "AI Containers Run as Non-Root (Least Privilege)",
        action,
        today,
    )
    return header + """
  rules:
    - name: require-non-root-security-context
      match:
        any:
        - resources:
            kinds:
            - Deployment
            - StatefulSet
            - Pod
            selector:
              matchLabels:
                mark-sentinel.io/ai-workload: "true"
      validate:
        message: >-
          [AI-AGENT-001] AI workload containers must run as non-root (securityContext.runAsNonRoot=true)
          to enforce least-privilege for agentic tool use.
        pattern:
          spec:
            =(template):
              spec:
                =(securityContext):
                  runAsNonRoot: true
                containers:
                - securityContext:
                    runAsNonRoot: true
                    allowPrivilegeEscalation: false
"""


def _policy_no_host_network(today: str, action: str) -> str:
    header = _meta(
        "mark-sentinel-ai-deploy-004",
        "AI-DEPLOY-004",
        "AI Workloads Must Not Use hostNetwork",
        action,
        today,
    )
    return header + """
  rules:
    - name: disallow-host-network
      match:
        any:
        - resources:
            kinds:
            - Deployment
            - StatefulSet
            - Pod
            selector:
              matchLabels:
                mark-sentinel.io/ai-workload: "true"
      validate:
        message: >-
          [AI-DEPLOY-004] AI workloads must not use hostNetwork=true. This bypasses
          network isolation and exposes the AI service to the host network.
        pattern:
          spec:
            =(template):
              spec:
                =(hostNetwork): false
"""


def _policy_require_tls_ingress(today: str, action: str) -> str:
    header = _meta(
        "mark-sentinel-ai-deploy-005",
        "AI-DEPLOY-005",
        "TLS Required on AI Service Ingress",
        action,
        today,
    )
    # Replace spec section for Ingress (different resource kind)
    header = header.replace(
        f'  validationFailureAction: {action}',
        f'  validationFailureAction: {action}'
    )
    return header + """
  rules:
    - name: require-tls-on-ai-ingress
      match:
        any:
        - resources:
            kinds:
            - Ingress
            selector:
              matchLabels:
                mark-sentinel.io/ai-workload: "true"
      validate:
        message: >-
          [AI-DEPLOY-005] AI service Ingress resources must configure TLS to enforce
          HTTPS-only connections. Add a tls[] entry with a valid secretName.
        pattern:
          spec:
            tls:
            - secretName: "?*"
"""


def _policy_require_pinned_image(today: str, action: str) -> str:
    header = _meta(
        "mark-sentinel-ai-supply-005",
        "AI-SUPPLY-005",
        "AI Container Images Must Use Pinned Tags",
        action,
        today,
    )
    return header + """
  rules:
    - name: disallow-latest-image-tag
      match:
        any:
        - resources:
            kinds:
            - Deployment
            - StatefulSet
            - Pod
            selector:
              matchLabels:
                mark-sentinel.io/ai-workload: "true"
      validate:
        message: >-
          [AI-SUPPLY-005] AI workload container images must not use the 'latest' tag or
          a floating tag. Pin to a specific digest or semantic version to prevent
          uncontrolled model/service updates.
        foreach:
          - list: "request.object.spec.template.spec.containers[]"
            deny:
              conditions:
                any:
                - key: "{{ element.image }}"
                  operator: Match
                  value: ".*:latest$"
                - key: "{{ element.image }}"
                  operator: NotMatch
                  value: ".+:.+"
"""


# Map check_id to policy generator so we can selectively include based on findings
_POLICY_MAP = {
    "AI-DEPLOY-001": _policy_no_plaintext_creds,
    "AI-DEPLOY-004": _policy_no_host_network,
    "AI-DEPLOY-005": _policy_require_tls_ingress,
    "AI-DEPLOY-006": _policy_require_resource_limits,
    "AI-AGENT-001": _policy_require_non_root,
    "AI-SUPPLY-005": _policy_require_pinned_image,
}


def format_kyverno(results: list, profile: dict, target: str, mode: str) -> str:
    today = str(date.today())
    profile_name = profile.get("name", "default")

    # Use Enforce for checks that failed/warned, Audit for everything else
    failed_ids = {r.check_id for r in results if r.status in ("FAIL", "WARN")}

    header_comment = f"""\
# M.A.R.K. Sentinel — Kyverno ClusterPolicy Bundle
# Profile  : {profile_name}
# Target   : {target}
# Generated: {today}
#
# Apply:   kubectl apply -f mark_sentinel_kyverno.yaml
# Remove:  kubectl delete -f mark_sentinel_kyverno.yaml
#
# These policies enforce M.A.R.K. Sentinel AI security controls on Kubernetes
# workloads. To target a workload, add the label:
#   {_AI_LABEL}
#
# Policies from this scan:
#   validationFailureAction: Enforce  — check FAILED or WARNED in this scan
#   validationFailureAction: Audit    — check passed (monitor only)
#
# To exempt a specific workload from a policy, add:
#   kyverno.io/exempt: "true"  label to the resource.

"""

    docs = [header_comment]
    for check_id, generator in _POLICY_MAP.items():
        action = "Enforce" if check_id in failed_ids else "Audit"
        docs.append(generator(today, action))

    return "\n---\n".join(docs)
