from datetime import date
from typing import List
from fpdf import FPDF

_SEV_ORDER = ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO']


class _ReportPDF(FPDF):
    def footer(self):
        # Position at 15 mm from bottom
        self.set_y(-15)
        self.set_font('Helvetica', size=9)
        footer_text = 'Confidential - Generated by M.A.R.K. Sentinel'
        self.cell(0, 6, footer_text, align='L')
        # page number
        self.cell(0, 6, f'Page {self.page_no()}', align='R')


def _count_by_status(results: List) -> dict:
    counts = {'total': len(results), 'pass': 0, 'warn': 0, 'fail': 0, 'skip': 0}
    for r in results:
        st = getattr(r, 'status', '').upper()
        if st == 'PASS':
            counts['pass'] += 1
        elif st == 'WARN':
            counts['warn'] += 1
        elif st == 'FAIL':
            counts['fail'] += 1
        elif st == 'SKIP':
            counts['skip'] += 1
    return counts


def _severity_fail_counts(results: List) -> dict:
    cc = {s: 0 for s in _SEV_ORDER}
    for r in results:
        if getattr(r, 'status', '').upper() == 'FAIL':
            sev = getattr(r, 'severity', '').upper() or 'INFO'
            if sev not in cc:
                cc[sev] = 0
            cc[sev] += 1
    return cc


def _safe_text(s: str) -> str:
    if s is None:
        return ''
    t = str(s)
    t = t.replace('\u2014', '-').replace('\u2013', '-')
    try:
        t.encode('latin-1')
        return t
    except UnicodeEncodeError:
        return t.encode('latin-1', errors='replace').decode('latin-1')


def format_pdf(results: List, profile: dict, target: str, mode: str = 'config', model: str = '') -> bytes:
    pdf = _ReportPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Header
    pdf.set_font('Helvetica', 'B', 14)
    pdf.cell(0, 8, _safe_text('M.A.R.K. Sentinel - AI Security Audit Report'), ln=1)
    pdf.set_font('Helvetica', size=10)
    pdf.cell(0, 6, _safe_text(f'Target: {target}'), ln=1)
    pdf.cell(0, 6, _safe_text(f'Profile: {profile.get("name", "")}'), ln=1)
    pdf.cell(0, 6, _safe_text(f'Date: {date.today().isoformat()}'), ln=1)
    pdf.cell(0, 6, _safe_text(f'Mode: {mode}'), ln=1)
    pdf.ln(4)

    # Executive Summary
    counts = _count_by_status(results)
    severity_counts = _severity_fail_counts(results)

    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(0, 7, _safe_text('Executive Summary'), ln=1)
    pdf.set_font('Helvetica', size=10)

    # Simple table for executive summary
    col_w = 45
    row_h = 6
    labels = [
        ('Total Checks', counts['total']),
        ('CRITICAL (fails)', severity_counts.get('CRITICAL', 0)),
        ('HIGH (fails)', severity_counts.get('HIGH', 0)),
        ('PASS', counts['pass']),
        ('WARN', counts['warn']),
        ('SKIP', counts['skip']),
    ]
    # Draw two columns of three rows
    x_start = pdf.get_x()
    for i, (label, val) in enumerate(labels):
        if i % 3 == 0 and i != 0:
            pdf.ln(row_h)
            pdf.set_x(x_start)
        pdf.cell(col_w, row_h, _safe_text(f'{label}: {val}'), border=0)
    pdf.ln(10)

    # Risk Summary by Severity
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(0, 7, _safe_text('Risk Summary by Severity (FAILs)'), ln=1)
    pdf.set_font('Helvetica', size=10)
    # Header row
    pdf.cell(40, 7, _safe_text('Severity'), border=1)
    pdf.cell(40, 7, _safe_text('Count'), border=1, ln=1)
    for sev in ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW']:
        pdf.cell(40, 7, _safe_text(sev), border=1)
        pdf.cell(40, 7, _safe_text(str(severity_counts.get(sev, 0))), border=1, ln=1)
    pdf.ln(6)

    # Findings - Critical & High (FAILs only)
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(0, 7, _safe_text('Findings - Critical & High (FAILs)'), ln=1)
    pdf.set_font('Helvetica', size=10)

    critical_high = [r for r in results if getattr(r, 'status', '').upper() == 'FAIL' and getattr(r, 'severity', '').upper() in ('CRITICAL', 'HIGH')]
    # sort CRITICAL first
    severity_rank = {'CRITICAL': 0, 'HIGH': 1}
    critical_high.sort(key=lambda r: severity_rank.get(getattr(r, 'severity', '').upper(), 99))

    for r in critical_high:
        pdf.set_font('Helvetica', 'B', 10)
        pdf.cell(0, 6, _safe_text(f"{r.check_id} - {r.title} [{r.severity}]") )
        pdf.ln(6)
        pdf.set_font('Helvetica', size=10)
        rem = getattr(r, 'remediation', '') or getattr(r, 'details', '') or ''
        # Keep remediation concise: limit to ~400 chars
        if len(rem) > 400:
            rem = rem[:400].rsplit('\n', 1)[0] + '...'
        pdf.multi_cell(0, 5, _safe_text(rem))
        pdf.ln(4)

    # All Findings Table
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(0, 7, _safe_text('All Findings'), ln=1)
    pdf.set_font('Helvetica', size=9)

    # Table header
    pdf.cell(30, 7, _safe_text('Check ID'), border=1)
    pdf.cell(80, 7, _safe_text('Title'), border=1)
    pdf.cell(25, 7, _safe_text('Status'), border=1)
    pdf.cell(25, 7, _safe_text('Severity'), border=1, ln=1)

    for r in results:
        x = pdf.get_x()
        y = pdf.get_y()
        pdf.cell(30, 6, _safe_text(str(getattr(r, 'check_id', ''))), border=1)
        pdf.multi_cell(80, 6, _safe_text(str(getattr(r, 'title', ''))), border=1)
        row_bottom = pdf.get_y()
        row_h = row_bottom - y
        pdf.set_xy(x + 110, y)
        pdf.cell(25, row_h, _safe_text(str(getattr(r, 'status', ''))), border=1)
        pdf.cell(25, row_h, _safe_text(str(getattr(r, 'severity', ''))), border=1)
        pdf.set_xy(x, row_bottom)

    out = pdf.output()
    if isinstance(out, str):
        out = out.encode('latin-1')
    return out
