#!/usr/bin/env bash
# Regenerate the nginx proxy-token map from all customer proxy_token.txt files.
#
# Reads each /opt/sentinel-data/<customer_id>/proxy_token.txt and emits an nginx
# map block: customer_id -> proxy_token_value. The map is included by the shared
# gateway vhost (arckon.conf) so nginx can set the right X-Sentinel-Proxy-Token
# per customer.
#
# Run after provisioning, restarting, or deleting a customer.
set -euo pipefail

DATA_ROOT="${SENTINEL_DATA_ROOT:-/opt/sentinel-data}"
NGINX_PROXY_TOKEN_DIR="${NGINX_PROXY_TOKEN_DIR:-/opt/sentinel-nginx/proxy-tokens}"
MAP_FILE="${NGINX_PROXY_TOKEN_MAP:-${NGINX_PROXY_TOKEN_DIR}/gateway-map.conf}"

# Ensure the target directory exists (test environments may not have it).
mkdir -p "$(dirname "$MAP_FILE")"

umask 077
tmp=$(mktemp)
{
    echo "# Auto-generated by regenerate_proxy_token_map.sh — do not edit."
    echo "# Maps authenticated customer_id -> per-customer proxy token value."
    echo "map \$sentinel_customer_id \$sentinel_proxy_token {"
    echo "    default \"\";"
    for dir in "$DATA_ROOT"/*/; do
        [ -d "$dir" ] || continue
        cid=$(basename "$dir")
        token_file="$dir/proxy_token.txt"
        if [ -f "$token_file" ]; then
            token=$(cat "$token_file")
            printf '    %s "%s";\n' "$cid" "$token"
        fi
    done
    echo "}"
} > "$tmp"

# Atomic move: nginx reads the old file until the rename completes.
mv "$tmp" "$MAP_FILE"
chmod 600 "$MAP_FILE"